# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lidar_interfaces/ObjectInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ObjectInfo(genpy.Message):
  _md5sum = "85c75bf95c45558608b5f8ca10538e49"
  _type = "lidar_interfaces/ObjectInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 objectCounts
float64[100] centerX
float64[100] centerY
float64[100] centerZ
float64[100] lengthX
float64[100] lengthY
float64[100] lengthZ
float64[100] minX
float64[100] minY
float64[100] minZ
float64[100] maxX
float64[100] maxY
float64[100] maxZ
int64[100] pixelX
int64[100] pixelY
"""
  __slots__ = ['objectCounts','centerX','centerY','centerZ','lengthX','lengthY','lengthZ','minX','minY','minZ','maxX','maxY','maxZ','pixelX','pixelY']
  _slot_types = ['int32','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','float64[100]','int64[100]','int64[100]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       objectCounts,centerX,centerY,centerZ,lengthX,lengthY,lengthZ,minX,minY,minZ,maxX,maxY,maxZ,pixelX,pixelY

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.objectCounts is None:
        self.objectCounts = 0
      if self.centerX is None:
        self.centerX = [0.] * 100
      if self.centerY is None:
        self.centerY = [0.] * 100
      if self.centerZ is None:
        self.centerZ = [0.] * 100
      if self.lengthX is None:
        self.lengthX = [0.] * 100
      if self.lengthY is None:
        self.lengthY = [0.] * 100
      if self.lengthZ is None:
        self.lengthZ = [0.] * 100
      if self.minX is None:
        self.minX = [0.] * 100
      if self.minY is None:
        self.minY = [0.] * 100
      if self.minZ is None:
        self.minZ = [0.] * 100
      if self.maxX is None:
        self.maxX = [0.] * 100
      if self.maxY is None:
        self.maxY = [0.] * 100
      if self.maxZ is None:
        self.maxZ = [0.] * 100
      if self.pixelX is None:
        self.pixelX = [0] * 100
      if self.pixelY is None:
        self.pixelY = [0] * 100
    else:
      self.objectCounts = 0
      self.centerX = [0.] * 100
      self.centerY = [0.] * 100
      self.centerZ = [0.] * 100
      self.lengthX = [0.] * 100
      self.lengthY = [0.] * 100
      self.lengthZ = [0.] * 100
      self.minX = [0.] * 100
      self.minY = [0.] * 100
      self.minZ = [0.] * 100
      self.maxX = [0.] * 100
      self.maxY = [0.] * 100
      self.maxZ = [0.] * 100
      self.pixelX = [0] * 100
      self.pixelY = [0] * 100

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.objectCounts
      buff.write(_get_struct_i().pack(_x))
      buff.write(_get_struct_100d().pack(*self.centerX))
      buff.write(_get_struct_100d().pack(*self.centerY))
      buff.write(_get_struct_100d().pack(*self.centerZ))
      buff.write(_get_struct_100d().pack(*self.lengthX))
      buff.write(_get_struct_100d().pack(*self.lengthY))
      buff.write(_get_struct_100d().pack(*self.lengthZ))
      buff.write(_get_struct_100d().pack(*self.minX))
      buff.write(_get_struct_100d().pack(*self.minY))
      buff.write(_get_struct_100d().pack(*self.minZ))
      buff.write(_get_struct_100d().pack(*self.maxX))
      buff.write(_get_struct_100d().pack(*self.maxY))
      buff.write(_get_struct_100d().pack(*self.maxZ))
      buff.write(_get_struct_100q().pack(*self.pixelX))
      buff.write(_get_struct_100q().pack(*self.pixelY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.objectCounts,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 800
      self.centerX = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.centerY = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.centerZ = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.lengthX = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.lengthY = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.lengthZ = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.minX = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.minY = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.minZ = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.maxX = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.maxY = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.maxZ = _get_struct_100d().unpack(str[start:end])
      start = end
      end += 800
      self.pixelX = _get_struct_100q().unpack(str[start:end])
      start = end
      end += 800
      self.pixelY = _get_struct_100q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.objectCounts
      buff.write(_get_struct_i().pack(_x))
      buff.write(self.centerX.tostring())
      buff.write(self.centerY.tostring())
      buff.write(self.centerZ.tostring())
      buff.write(self.lengthX.tostring())
      buff.write(self.lengthY.tostring())
      buff.write(self.lengthZ.tostring())
      buff.write(self.minX.tostring())
      buff.write(self.minY.tostring())
      buff.write(self.minZ.tostring())
      buff.write(self.maxX.tostring())
      buff.write(self.maxY.tostring())
      buff.write(self.maxZ.tostring())
      buff.write(self.pixelX.tostring())
      buff.write(self.pixelY.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.objectCounts,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 800
      self.centerX = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.centerY = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.centerZ = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.lengthX = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.lengthY = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.lengthZ = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.minX = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.minY = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.minZ = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.maxX = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.maxY = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.maxZ = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=100)
      start = end
      end += 800
      self.pixelX = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=100)
      start = end
      end += 800
      self.pixelY = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=100)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_100d = None
def _get_struct_100d():
    global _struct_100d
    if _struct_100d is None:
        _struct_100d = struct.Struct("<100d")
    return _struct_100d
_struct_100q = None
def _get_struct_100q():
    global _struct_100q
    if _struct_100q is None:
        _struct_100q = struct.Struct("<100q")
    return _struct_100q
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
