// Generated by gencpp from file lidar_interfaces/ObjectInfo.msg
// DO NOT EDIT!


#ifndef LIDAR_INTERFACES_MESSAGE_OBJECTINFO_H
#define LIDAR_INTERFACES_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_interfaces
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : objectCounts(0)
    , centerX()
    , centerY()
    , centerZ()
    , lengthX()
    , lengthY()
    , lengthZ()
    , minX()
    , minY()
    , minZ()
    , maxX()
    , maxY()
    , maxZ()
    , pixelX()
    , pixelY()  {
      centerX.assign(0.0);

      centerY.assign(0.0);

      centerZ.assign(0.0);

      lengthX.assign(0.0);

      lengthY.assign(0.0);

      lengthZ.assign(0.0);

      minX.assign(0.0);

      minY.assign(0.0);

      minZ.assign(0.0);

      maxX.assign(0.0);

      maxY.assign(0.0);

      maxZ.assign(0.0);

      pixelX.assign(0);

      pixelY.assign(0);
  }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : objectCounts(0)
    , centerX()
    , centerY()
    , centerZ()
    , lengthX()
    , lengthY()
    , lengthZ()
    , minX()
    , minY()
    , minZ()
    , maxX()
    , maxY()
    , maxZ()
    , pixelX()
    , pixelY()  {
  (void)_alloc;
      centerX.assign(0.0);

      centerY.assign(0.0);

      centerZ.assign(0.0);

      lengthX.assign(0.0);

      lengthY.assign(0.0);

      lengthZ.assign(0.0);

      minX.assign(0.0);

      minY.assign(0.0);

      minZ.assign(0.0);

      maxX.assign(0.0);

      maxY.assign(0.0);

      maxZ.assign(0.0);

      pixelX.assign(0);

      pixelY.assign(0);
  }



   typedef int32_t _objectCounts_type;
  _objectCounts_type objectCounts;

   typedef boost::array<double, 100>  _centerX_type;
  _centerX_type centerX;

   typedef boost::array<double, 100>  _centerY_type;
  _centerY_type centerY;

   typedef boost::array<double, 100>  _centerZ_type;
  _centerZ_type centerZ;

   typedef boost::array<double, 100>  _lengthX_type;
  _lengthX_type lengthX;

   typedef boost::array<double, 100>  _lengthY_type;
  _lengthY_type lengthY;

   typedef boost::array<double, 100>  _lengthZ_type;
  _lengthZ_type lengthZ;

   typedef boost::array<double, 100>  _minX_type;
  _minX_type minX;

   typedef boost::array<double, 100>  _minY_type;
  _minY_type minY;

   typedef boost::array<double, 100>  _minZ_type;
  _minZ_type minZ;

   typedef boost::array<double, 100>  _maxX_type;
  _maxX_type maxX;

   typedef boost::array<double, 100>  _maxY_type;
  _maxY_type maxY;

   typedef boost::array<double, 100>  _maxZ_type;
  _maxZ_type maxZ;

   typedef boost::array<int64_t, 100>  _pixelX_type;
  _pixelX_type pixelX;

   typedef boost::array<int64_t, 100>  _pixelY_type;
  _pixelY_type pixelY;





  typedef boost::shared_ptr< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::lidar_interfaces::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::lidar_interfaces::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::lidar_interfaces::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_interfaces::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_interfaces::ObjectInfo_<ContainerAllocator1> & lhs, const ::lidar_interfaces::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return lhs.objectCounts == rhs.objectCounts &&
    lhs.centerX == rhs.centerX &&
    lhs.centerY == rhs.centerY &&
    lhs.centerZ == rhs.centerZ &&
    lhs.lengthX == rhs.lengthX &&
    lhs.lengthY == rhs.lengthY &&
    lhs.lengthZ == rhs.lengthZ &&
    lhs.minX == rhs.minX &&
    lhs.minY == rhs.minY &&
    lhs.minZ == rhs.minZ &&
    lhs.maxX == rhs.maxX &&
    lhs.maxY == rhs.maxY &&
    lhs.maxZ == rhs.maxZ &&
    lhs.pixelX == rhs.pixelX &&
    lhs.pixelY == rhs.pixelY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_interfaces::ObjectInfo_<ContainerAllocator1> & lhs, const ::lidar_interfaces::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85c75bf95c45558608b5f8ca10538e49";
  }

  static const char* value(const ::lidar_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85c75bf95c455586ULL;
  static const uint64_t static_value2 = 0x08b5f8ca10538e49ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_interfaces/ObjectInfo";
  }

  static const char* value(const ::lidar_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 objectCounts\n"
"float64[100] centerX\n"
"float64[100] centerY\n"
"float64[100] centerZ\n"
"float64[100] lengthX\n"
"float64[100] lengthY\n"
"float64[100] lengthZ\n"
"float64[100] minX\n"
"float64[100] minY\n"
"float64[100] minZ\n"
"float64[100] maxX\n"
"float64[100] maxY\n"
"float64[100] maxZ\n"
"int64[100] pixelX\n"
"int64[100] pixelY\n"
;
  }

  static const char* value(const ::lidar_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectCounts);
      stream.next(m.centerX);
      stream.next(m.centerY);
      stream.next(m.centerZ);
      stream.next(m.lengthX);
      stream.next(m.lengthY);
      stream.next(m.lengthZ);
      stream.next(m.minX);
      stream.next(m.minY);
      stream.next(m.minZ);
      stream.next(m.maxX);
      stream.next(m.maxY);
      stream.next(m.maxZ);
      stream.next(m.pixelX);
      stream.next(m.pixelY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_interfaces::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_interfaces::ObjectInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "objectCounts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.objectCounts);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "centerX: ";
    if (v.centerX.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.centerX.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.centerX[i]);
    }
    if (v.centerX.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "centerY: ";
    if (v.centerY.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.centerY.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.centerY[i]);
    }
    if (v.centerY.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "centerZ: ";
    if (v.centerZ.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.centerZ.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.centerZ[i]);
    }
    if (v.centerZ.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lengthX: ";
    if (v.lengthX.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lengthX.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lengthX[i]);
    }
    if (v.lengthX.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lengthY: ";
    if (v.lengthY.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lengthY.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lengthY[i]);
    }
    if (v.lengthY.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lengthZ: ";
    if (v.lengthZ.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lengthZ.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lengthZ[i]);
    }
    if (v.lengthZ.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minX: ";
    if (v.minX.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.minX.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.minX[i]);
    }
    if (v.minX.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minY: ";
    if (v.minY.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.minY.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.minY[i]);
    }
    if (v.minY.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "minZ: ";
    if (v.minZ.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.minZ.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.minZ[i]);
    }
    if (v.minZ.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "maxX: ";
    if (v.maxX.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.maxX.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.maxX[i]);
    }
    if (v.maxX.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "maxY: ";
    if (v.maxY.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.maxY.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.maxY[i]);
    }
    if (v.maxY.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "maxZ: ";
    if (v.maxZ.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.maxZ.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.maxZ[i]);
    }
    if (v.maxZ.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pixelX: ";
    if (v.pixelX.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pixelX.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int64_t>::stream(s, true ? std::string() : indent + "    ", v.pixelX[i]);
    }
    if (v.pixelX.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pixelY: ";
    if (v.pixelY.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pixelY.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int64_t>::stream(s, true ? std::string() : indent + "    ", v.pixelY[i]);
    }
    if (v.pixelY.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_INTERFACES_MESSAGE_OBJECTINFO_H
