(cl:in-package lidar_interfaces-msg)
(cl:export '(OBJECTCOUNTS-VAL
          OBJECTCOUNTS
          CENTERX-VAL
          CENTERX
          CENTERY-VAL
          CENTERY
          CENTERZ-VAL
          CENTERZ
          LENGTHX-VAL
          LENGTHX
          LENGTHY-VAL
          LENGTHY
          LENGTHZ-VAL
          LENGTHZ
          MINX-VAL
          MINX
          MINY-VAL
          MINY
          MINZ-VAL
          MINZ
          MAXX-VAL
          MAXX
          MAXY-VAL
          MAXY
          MAXZ-VAL
          MAXZ
          PIXELX-VAL
          PIXELX
          PIXELY-VAL
          PIXELY
))