//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the safety_supervisor package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __safety_supervisor__SAFETYSUPERVISORPARAMETERSCONFIG_H__
#define __safety_supervisor__SAFETYSUPERVISORPARAMETERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace safety_supervisor
{
  class SafetySupervisorParametersConfigStatics;

  class SafetySupervisorParametersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(SafetySupervisorParametersConfig &config, const SafetySupervisorParametersConfig &max, const SafetySupervisorParametersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const SafetySupervisorParametersConfig &config1, const SafetySupervisorParametersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, SafetySupervisorParametersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const SafetySupervisorParametersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SafetySupervisorParametersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const SafetySupervisorParametersConfig &config) const = 0;
      virtual void getValue(const SafetySupervisorParametersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T SafetySupervisorParametersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T SafetySupervisorParametersConfig::* field;

      virtual void clamp(SafetySupervisorParametersConfig &config, const SafetySupervisorParametersConfig &max, const SafetySupervisorParametersConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const SafetySupervisorParametersConfig &config1, const SafetySupervisorParametersConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, SafetySupervisorParametersConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const SafetySupervisorParametersConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SafetySupervisorParametersConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const SafetySupervisorParametersConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const SafetySupervisorParametersConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, SafetySupervisorParametersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, SafetySupervisorParametersConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<SafetySupervisorParametersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(SafetySupervisorParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("path_width_margin"==(*_i)->name){path_width_margin = boost::any_cast<double>(val);}
        if("max_check_distance"==(*_i)->name){max_check_distance = boost::any_cast<double>(val);}
        if("min_check_distance"==(*_i)->name){min_check_distance = boost::any_cast<double>(val);}
        if("lookahead_time"==(*_i)->name){lookahead_time = boost::any_cast<double>(val);}
        if("roi_speed_curve"==(*_i)->name){roi_speed_curve = boost::any_cast<double>(val);}
        if("detect_count_threshold"==(*_i)->name){detect_count_threshold = boost::any_cast<int>(val);}
        if("clear_count_threshold"==(*_i)->name){clear_count_threshold = boost::any_cast<int>(val);}
        if("stale_clear_count_threshold"==(*_i)->name){stale_clear_count_threshold = boost::any_cast<int>(val);}
        if("data_timeout_sec"==(*_i)->name){data_timeout_sec = boost::any_cast<double>(val);}
        if("margin_step"==(*_i)->name){margin_step = boost::any_cast<double>(val);}
      }
    }

    double path_width_margin;
double max_check_distance;
double min_check_distance;
double lookahead_time;
double roi_speed_curve;
int detect_count_threshold;
int clear_count_threshold;
int stale_clear_count_threshold;
double data_timeout_sec;
double margin_step;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double path_width_margin;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_check_distance;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_check_distance;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lookahead_time;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double roi_speed_curve;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int detect_count_threshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int clear_count_threshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int stale_clear_count_threshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double data_timeout_sec;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double margin_step;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("SafetySupervisorParametersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const SafetySupervisorParametersConfig &__max__ = __getMax__();
      const SafetySupervisorParametersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const SafetySupervisorParametersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const SafetySupervisorParametersConfig &__getDefault__();
    static const SafetySupervisorParametersConfig &__getMax__();
    static const SafetySupervisorParametersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const SafetySupervisorParametersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void SafetySupervisorParametersConfig::ParamDescription<std::string>::clamp(SafetySupervisorParametersConfig &config, const SafetySupervisorParametersConfig &max, const SafetySupervisorParametersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class SafetySupervisorParametersConfigStatics
  {
    friend class SafetySupervisorParametersConfig;

    SafetySupervisorParametersConfigStatics()
    {
SafetySupervisorParametersConfig::GroupDescription<SafetySupervisorParametersConfig::DEFAULT, SafetySupervisorParametersConfig> Default("Default", "", 0, 0, true, &SafetySupervisorParametersConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_width_margin = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_width_margin = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_width_margin = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("path_width_margin", "double", 0, "Half corridor width margin (m)", "", &SafetySupervisorParametersConfig::path_width_margin)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("path_width_margin", "double", 0, "Half corridor width margin (m)", "", &SafetySupervisorParametersConfig::path_width_margin)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_check_distance = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_check_distance = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_check_distance = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("max_check_distance", "double", 0, "Maximum collision check distance (m)", "", &SafetySupervisorParametersConfig::max_check_distance)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("max_check_distance", "double", 0, "Maximum collision check distance (m)", "", &SafetySupervisorParametersConfig::max_check_distance)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_check_distance = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_check_distance = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_check_distance = 0.7;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("min_check_distance", "double", 0, "Minimum collision check distance (m)", "", &SafetySupervisorParametersConfig::min_check_distance)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("min_check_distance", "double", 0, "Minimum collision check distance (m)", "", &SafetySupervisorParametersConfig::min_check_distance)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lookahead_time = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lookahead_time = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lookahead_time = 0.6;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("lookahead_time", "double", 0, "Lookahead time for collision checking (s)", "", &SafetySupervisorParametersConfig::lookahead_time)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("lookahead_time", "double", 0, "Lookahead time for collision checking (s)", "", &SafetySupervisorParametersConfig::lookahead_time)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roi_speed_curve = -1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roi_speed_curve = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roi_speed_curve = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("roi_speed_curve", "double", 0, "ROI speed sensitivity curve: positive=low-speed insensitive, negative=low-speed sensitive", "", &SafetySupervisorParametersConfig::roi_speed_curve)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("roi_speed_curve", "double", 0, "ROI speed sensitivity curve: positive=low-speed insensitive, negative=low-speed sensitive", "", &SafetySupervisorParametersConfig::roi_speed_curve)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.detect_count_threshold = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.detect_count_threshold = 100;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.detect_count_threshold = 2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<int>("detect_count_threshold", "int", 0, "Consecutive hazard detections required", "", &SafetySupervisorParametersConfig::detect_count_threshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<int>("detect_count_threshold", "int", 0, "Consecutive hazard detections required", "", &SafetySupervisorParametersConfig::detect_count_threshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.clear_count_threshold = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.clear_count_threshold = 100;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.clear_count_threshold = 4;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<int>("clear_count_threshold", "int", 0, "Consecutive safe detections required", "", &SafetySupervisorParametersConfig::clear_count_threshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<int>("clear_count_threshold", "int", 0, "Consecutive safe detections required", "", &SafetySupervisorParametersConfig::clear_count_threshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stale_clear_count_threshold = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stale_clear_count_threshold = 100;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stale_clear_count_threshold = 2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<int>("stale_clear_count_threshold", "int", 0, "Consecutive stale cycles required to clear", "", &SafetySupervisorParametersConfig::stale_clear_count_threshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<int>("stale_clear_count_threshold", "int", 0, "Consecutive stale cycles required to clear", "", &SafetySupervisorParametersConfig::stale_clear_count_threshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.data_timeout_sec = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.data_timeout_sec = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.data_timeout_sec = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("data_timeout_sec", "double", 0, "Input freshness timeout (s)", "", &SafetySupervisorParametersConfig::data_timeout_sec)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("data_timeout_sec", "double", 0, "Input freshness timeout (s)", "", &SafetySupervisorParametersConfig::data_timeout_sec)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.margin_step = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.margin_step = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.margin_step = 0.01;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("margin_step", "double", 0, "Per-point corridor margin decay (m)", "", &SafetySupervisorParametersConfig::margin_step)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr(new SafetySupervisorParametersConfig::ParamDescription<double>("margin_step", "double", 0, "Per-point corridor margin decay (m)", "", &SafetySupervisorParametersConfig::margin_step)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(SafetySupervisorParametersConfig::AbstractGroupDescriptionConstPtr(new SafetySupervisorParametersConfig::GroupDescription<SafetySupervisorParametersConfig::DEFAULT, SafetySupervisorParametersConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<SafetySupervisorParametersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<SafetySupervisorParametersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    SafetySupervisorParametersConfig __max__;
    SafetySupervisorParametersConfig __min__;
    SafetySupervisorParametersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const SafetySupervisorParametersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static SafetySupervisorParametersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &SafetySupervisorParametersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const SafetySupervisorParametersConfig &SafetySupervisorParametersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const SafetySupervisorParametersConfig &SafetySupervisorParametersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const SafetySupervisorParametersConfig &SafetySupervisorParametersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<SafetySupervisorParametersConfig::AbstractParamDescriptionConstPtr> &SafetySupervisorParametersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<SafetySupervisorParametersConfig::AbstractGroupDescriptionConstPtr> &SafetySupervisorParametersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const SafetySupervisorParametersConfigStatics *SafetySupervisorParametersConfig::__get_statics__()
  {
    const static SafetySupervisorParametersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = SafetySupervisorParametersConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __SAFETYSUPERVISORPARAMETERSRECONFIGURATOR_H__
