//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the vision_pkg package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __vision_pkg__VISIONCONFIG_H__
#define __vision_pkg__VISIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace vision_pkg
{
  class VisionConfigStatics;

  class VisionConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(VisionConfig &config, const VisionConfig &max, const VisionConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const VisionConfig &config1, const VisionConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, VisionConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const VisionConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, VisionConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const VisionConfig &config) const = 0;
      virtual void getValue(const VisionConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T VisionConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T VisionConfig::* field;

      virtual void clamp(VisionConfig &config, const VisionConfig &max, const VisionConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const VisionConfig &config1, const VisionConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, VisionConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const VisionConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, VisionConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const VisionConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const VisionConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, VisionConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, VisionConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<VisionConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(VisionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("bilateral_d"==(*_i)->name){bilateral_d = boost::any_cast<int>(val);}
        if("bilateral_color"==(*_i)->name){bilateral_color = boost::any_cast<int>(val);}
        if("bilateral_space"==(*_i)->name){bilateral_space = boost::any_cast<int>(val);}
        if("canny_low"==(*_i)->name){canny_low = boost::any_cast<int>(val);}
        if("canny_high"==(*_i)->name){canny_high = boost::any_cast<int>(val);}
        if("camera_height"==(*_i)->name){camera_height = boost::any_cast<double>(val);}
        if("camera_pitch"==(*_i)->name){camera_pitch = boost::any_cast<double>(val);}
        if("camera_fov"==(*_i)->name){camera_fov = boost::any_cast<int>(val);}
        if("bev_length"==(*_i)->name){bev_length = boost::any_cast<double>(val);}
        if("bev_width"==(*_i)->name){bev_width = boost::any_cast<double>(val);}
        if("n_windows"==(*_i)->name){n_windows = boost::any_cast<int>(val);}
        if("sw_margin"==(*_i)->name){sw_margin = boost::any_cast<int>(val);}
        if("minpix"==(*_i)->name){minpix = boost::any_cast<int>(val);}
        if("minpix_bottom"==(*_i)->name){minpix_bottom = boost::any_cast<int>(val);}
        if("max_gap_windows"==(*_i)->name){max_gap_windows = boost::any_cast<int>(val);}
        if("sw_bottom_offset"==(*_i)->name){sw_bottom_offset = boost::any_cast<int>(val);}
        if("minlanepix"==(*_i)->name){minlanepix = boost::any_cast<int>(val);}
        if("poly_order"==(*_i)->name){poly_order = boost::any_cast<int>(val);}
        if("lane_width_px"==(*_i)->name){lane_width_px = boost::any_cast<int>(val);}
        if("min_lane_width_px"==(*_i)->name){min_lane_width_px = boost::any_cast<int>(val);}
        if("smooth_alpha"==(*_i)->name){smooth_alpha = boost::any_cast<double>(val);}
        if("sw_pred_amp"==(*_i)->name){sw_pred_amp = boost::any_cast<double>(val);}
        if("sw_curve_ratio"==(*_i)->name){sw_curve_ratio = boost::any_cast<double>(val);}
        if("publish_debug_images"==(*_i)->name){publish_debug_images = boost::any_cast<bool>(val);}
        if("save_config"==(*_i)->name){save_config = boost::any_cast<bool>(val);}
      }
    }

    int bilateral_d;
int bilateral_color;
int bilateral_space;
int canny_low;
int canny_high;
double camera_height;
double camera_pitch;
int camera_fov;
double bev_length;
double bev_width;
int n_windows;
int sw_margin;
int minpix;
int minpix_bottom;
int max_gap_windows;
int sw_bottom_offset;
int minlanepix;
int poly_order;
int lane_width_px;
int min_lane_width_px;
double smooth_alpha;
double sw_pred_amp;
double sw_curve_ratio;
bool publish_debug_images;
bool save_config;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int bilateral_d;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int bilateral_color;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int bilateral_space;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int canny_low;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int canny_high;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double camera_height;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double camera_pitch;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int camera_fov;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double bev_length;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double bev_width;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int n_windows;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int sw_margin;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minpix;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minpix_bottom;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_gap_windows;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int sw_bottom_offset;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minlanepix;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int poly_order;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int lane_width_px;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_lane_width_px;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double smooth_alpha;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sw_pred_amp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double sw_curve_ratio;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool publish_debug_images;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool save_config;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("VisionConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const VisionConfig &__max__ = __getMax__();
      const VisionConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const VisionConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const VisionConfig &__getDefault__();
    static const VisionConfig &__getMax__();
    static const VisionConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const VisionConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void VisionConfig::ParamDescription<std::string>::clamp(VisionConfig &config, const VisionConfig &max, const VisionConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class VisionConfigStatics
  {
    friend class VisionConfig;

    VisionConfigStatics()
    {
VisionConfig::GroupDescription<VisionConfig::DEFAULT, VisionConfig> Default("Default", "", 0, 0, true, &VisionConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bilateral_d = 3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bilateral_d = 15;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bilateral_d = 9;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("bilateral_d", "int", 0, "Bilateral Filter d", "", &VisionConfig::bilateral_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("bilateral_d", "int", 0, "Bilateral Filter d", "", &VisionConfig::bilateral_d)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bilateral_color = 10;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bilateral_color = 200;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bilateral_color = 30;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("bilateral_color", "int", 0, "Bilateral Filter sigmaColor", "", &VisionConfig::bilateral_color)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("bilateral_color", "int", 0, "Bilateral Filter sigmaColor", "", &VisionConfig::bilateral_color)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bilateral_space = 10;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bilateral_space = 200;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bilateral_space = 30;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("bilateral_space", "int", 0, "Bilateral Filter sigmaSpace", "", &VisionConfig::bilateral_space)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("bilateral_space", "int", 0, "Bilateral Filter sigmaSpace", "", &VisionConfig::bilateral_space)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.canny_low = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.canny_low = 255;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.canny_low = 50;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("canny_low", "int", 0, "Canny Low Threshold", "", &VisionConfig::canny_low)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("canny_low", "int", 0, "Canny Low Threshold", "", &VisionConfig::canny_low)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.canny_high = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.canny_high = 255;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.canny_high = 120;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("canny_high", "int", 0, "Canny High Threshold", "", &VisionConfig::canny_high)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("canny_high", "int", 0, "Canny High Threshold", "", &VisionConfig::canny_high)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.camera_height = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.camera_height = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.camera_height = 1.2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("camera_height", "double", 0, "Camera Height (m)", "", &VisionConfig::camera_height)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("camera_height", "double", 0, "Camera Height (m)", "", &VisionConfig::camera_height)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.camera_pitch = -90.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.camera_pitch = 90.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.camera_pitch = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("camera_pitch", "double", 0, "Camera Pitch (deg)", "", &VisionConfig::camera_pitch)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("camera_pitch", "double", 0, "Camera Pitch (deg)", "", &VisionConfig::camera_pitch)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.camera_fov = 30;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.camera_fov = 150;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.camera_fov = 103;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("camera_fov", "int", 0, "Camera Horizontal FOV (deg)", "", &VisionConfig::camera_fov)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("camera_fov", "int", 0, "Camera Horizontal FOV (deg)", "", &VisionConfig::camera_fov)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bev_length = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bev_length = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bev_length = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("bev_length", "double", 0, "BEV ROI Length (m)", "", &VisionConfig::bev_length)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("bev_length", "double", 0, "BEV ROI Length (m)", "", &VisionConfig::bev_length)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bev_width = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bev_width = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bev_width = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("bev_width", "double", 0, "BEV ROI Width (m)", "", &VisionConfig::bev_width)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("bev_width", "double", 0, "BEV ROI Width (m)", "", &VisionConfig::bev_width)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.n_windows = 5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.n_windows = 80;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.n_windows = 10;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("n_windows", "int", 0, "Number of Windows", "", &VisionConfig::n_windows)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("n_windows", "int", 0, "Number of Windows", "", &VisionConfig::n_windows)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sw_margin = 5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sw_margin = 200;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sw_margin = 30;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("sw_margin", "int", 0, "Window Search Margin", "", &VisionConfig::sw_margin)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("sw_margin", "int", 0, "Window Search Margin", "", &VisionConfig::sw_margin)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minpix = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minpix = 100;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minpix = 10;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("minpix", "int", 0, "Min Pixels per Window", "", &VisionConfig::minpix)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("minpix", "int", 0, "Min Pixels per Window", "", &VisionConfig::minpix)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minpix_bottom = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minpix_bottom = 200;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minpix_bottom = 10;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("minpix_bottom", "int", 0, "Min Pixels (Bottom)", "", &VisionConfig::minpix_bottom)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("minpix_bottom", "int", 0, "Min Pixels (Bottom)", "", &VisionConfig::minpix_bottom)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_gap_windows = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_gap_windows = 5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_gap_windows = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("max_gap_windows", "int", 0, "Max Empty Windows", "", &VisionConfig::max_gap_windows)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("max_gap_windows", "int", 0, "Max Empty Windows", "", &VisionConfig::max_gap_windows)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sw_bottom_offset = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sw_bottom_offset = 100;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sw_bottom_offset = 50;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("sw_bottom_offset", "int", 0, "Bottom Offset (px)", "", &VisionConfig::sw_bottom_offset)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("sw_bottom_offset", "int", 0, "Bottom Offset (px)", "", &VisionConfig::sw_bottom_offset)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minlanepix = 50;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minlanepix = 2000;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minlanepix = 200;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("minlanepix", "int", 0, "Min Total Lane Pixels", "", &VisionConfig::minlanepix)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("minlanepix", "int", 0, "Min Total Lane Pixels", "", &VisionConfig::minlanepix)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.poly_order = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.poly_order = 3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.poly_order = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("poly_order", "int", 0, "Polynomial Order", "", &VisionConfig::poly_order)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("poly_order", "int", 0, "Polynomial Order", "", &VisionConfig::poly_order)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lane_width_px = 80;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lane_width_px = 1000;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lane_width_px = 100;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("lane_width_px", "int", 0, "Default Lane Width (px)", "", &VisionConfig::lane_width_px)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("lane_width_px", "int", 0, "Default Lane Width (px)", "", &VisionConfig::lane_width_px)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_lane_width_px = 50;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_lane_width_px = 600;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_lane_width_px = 200;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("min_lane_width_px", "int", 0, "Min Allowed Spacing (px)", "", &VisionConfig::min_lane_width_px)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<int>("min_lane_width_px", "int", 0, "Min Allowed Spacing (px)", "", &VisionConfig::min_lane_width_px)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.smooth_alpha = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.smooth_alpha = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.smooth_alpha = 0.9;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("smooth_alpha", "double", 0, "Fit Smoothing Alpha", "", &VisionConfig::smooth_alpha)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("smooth_alpha", "double", 0, "Fit Smoothing Alpha", "", &VisionConfig::smooth_alpha)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sw_pred_amp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sw_pred_amp = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sw_pred_amp = 1.2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("sw_pred_amp", "double", 0, "Curve Pred Amplification", "", &VisionConfig::sw_pred_amp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("sw_pred_amp", "double", 0, "Curve Pred Amplification", "", &VisionConfig::sw_pred_amp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.sw_curve_ratio = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.sw_curve_ratio = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.sw_curve_ratio = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("sw_curve_ratio", "double", 0, "Curve Search Margin Ratio", "", &VisionConfig::sw_curve_ratio)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<double>("sw_curve_ratio", "double", 0, "Curve Search Margin Ratio", "", &VisionConfig::sw_curve_ratio)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publish_debug_images = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publish_debug_images = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publish_debug_images = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<bool>("publish_debug_images", "bool", 0, "Publish Debug Topics (Heavy)", "", &VisionConfig::publish_debug_images)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<bool>("publish_debug_images", "bool", 0, "Publish Debug Topics (Heavy)", "", &VisionConfig::publish_debug_images)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.save_config = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.save_config = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.save_config = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<bool>("save_config", "bool", 0, "Save Parameters to config.py", "", &VisionConfig::save_config)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(VisionConfig::AbstractParamDescriptionConstPtr(new VisionConfig::ParamDescription<bool>("save_config", "bool", 0, "Save Parameters to config.py", "", &VisionConfig::save_config)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(VisionConfig::AbstractGroupDescriptionConstPtr(new VisionConfig::GroupDescription<VisionConfig::DEFAULT, VisionConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<VisionConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<VisionConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<VisionConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    VisionConfig __max__;
    VisionConfig __min__;
    VisionConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const VisionConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static VisionConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &VisionConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const VisionConfig &VisionConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const VisionConfig &VisionConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const VisionConfig &VisionConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<VisionConfig::AbstractParamDescriptionConstPtr> &VisionConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<VisionConfig::AbstractGroupDescriptionConstPtr> &VisionConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const VisionConfigStatics *VisionConfig::__get_statics__()
  {
    const static VisionConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = VisionConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __VISIONRECONFIGURATOR_H__
